spring.application.name=appGrupo12Consumidor
spring.main.web-application-type=none
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
fibonacci.processing-delay-ms=${FIBONACCI_PROCESSING_DELAY_MS:20000}